name: custom-emu

channels:
  - conda-forge
  - bioconda
  - nodefaults

dependencies:
  - biopython
  - python >=3.6,<=3.8.12
  - pysam >=0.15
  - numpy >=1.11
  - pandas >=1.1
  - flatten-dict
  - minimap2 >=2.22
